# Secret с секретными переменными окружения Query Module
# DB credentials + OAuth client credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qm.fullname" . }}-secret
  labels:
    {{- include "qm.labels" . | nindent 4 }}
type: Opaque
stringData:
  # --- PostgreSQL credentials ---
  QM_DB_USER: {{ .Values.database.user | quote }}
  QM_DB_PASSWORD: {{ .Values.database.password | quote }}
  # --- OAuth credentials (Client Credentials для SA) ---
  QM_CLIENT_ID: {{ .Values.oauth.clientId | quote }}
  QM_CLIENT_SECRET: {{ .Values.oauth.clientSecret | quote }}
